[package]
name = "batcher_contract"
type = "contract"
authors = [""]
compiler_version = ">=0.27.0"

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.35.1', directory = 'noir-projects/aztec-nr/aztec' }
noir_elgamal = { path = "../noir_elgamal" }