[package]
name = "uniswap_contract"
type = "contract"
authors = ["porco"]
compiler_version = ">=0.26.0"

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.32.1', directory = 'noir-projects/aztec-nr/aztec' }
authwit = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.32.1', directory = 'noir-projects/aztec-nr/authwit' }