[package]
name = "dca"
type = "contract"
authors = [""]
compiler_version = ">=0.26.0"

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.33.0', directory = 'noir-projects/aztec-nr/aztec' }
